apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v18
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v18
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v18
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v18
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: reg.local:5000/heapster:v0.18.2 
        #- image: gcr.io/google_containers/heapster:v0.18.2
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 600m
              memory: 500Mi 
            requests:
              cpu: 600m
              memory: 500Mi 
          command:
            - /heapster
            - --source=kubernetes:''
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --stats_resolution=30s
            - --sink_frequency=1m
